import type { Metadata } from "next"
import { Krona_One } from "next/font/google"
import { Public_Sans } from "next/font/google"

import { ThemeProvider } from "@/components/context/ThemeProvider"
import { getThemeCookie } from "@/server/utils"

import { ClientBodyWrapper } from "./ClientBodyWrapper"
import "./globals.css"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

const publicSans = Public_Sans({
  subsets: ["latin"],
  variable: "--font-public-sans",
})

const kronaOne = Krona_One({
  weight: ["400"],
  subsets: ["latin"],
  variable: "--font-krona-one",
})

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const theme = await getThemeCookie()

  return (
    <html
      lang="en"
      className={`${publicSans.className} ${publicSans.variable} ${kronaOne.variable} min-h-screen`}
    >
      <ThemeProvider initialTheme={theme}>
        <ClientBodyWrapper>{children}</ClientBodyWrapper>
      </ThemeProvider>
    </html>
  )
}
